### ISSUE TITLE
Macro CV mapping not saved?

### ISSUE THREAD

**Issue by LarsDanielTerkelsen** [grimepoch/structure_bugs#8]
If I map a CV input to a Macro, Structure warns me, that I have an unsaved performance. So I save the performance. Then on reboot, plus loading the performance I saved, the CV mapping has not been remembered. This does not seem right to me.

**Comment by grimepoch** [comment]
The bug there currently is it should not warn of the performance needing to be saved as I had not implemented the macro CV saving yet, however, since I'd rather save the macro CV settings, I will add that to the list.  Because I'd like them to stay with the performance, especially if I have a CC mapped to them and am using another controller for a function.

**Comment by grimepoch** [comment]
This will be coming in v3.4, just implemented it tonight.  Saves with performance.

**Comment by LarsDanielTerkelsen** [comment]
👍🏼
